services:
  - type: web
    name: factory-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://muditert34_db_user:Zr9uAwt7oB9TwhDk@cluster0.tbsntnb.mongodb.net/?appName=Cluster0
      - key: DB_NAME
        value: factory_db
      - key: PORT
        value: 10000
